- name: Déploiement du conteneur
  hosts: all
  become: true

  tasks:
    
    - name: Sauvegarde de l'image Docker en tant que fichier tar
      command: docker save lstar974/serveur -o /root/serveur.tar

    - name: Création du conteneur temporaire
      docker_container:
        name: my_temp_container
        image: lstar974/serveur
        command: sleep infinity
        detach: yes
        privileged: yes
      register: temp_container_output

    - name: Copie des fichiers de configuration depuis le conteneur
      docker_container:
        name: my_temp_container
        copy:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          direction: from_container
      loop:
        - { src: "/etc/mysql/my.cnf", dest: "/etc/mysql/my.cnf" }
        - { src: "/etc/ssl/private/apache-selfsigned.key", dest: "/etc/ssl/private/apache-selfsigned.key" }
        - { src: "/etc/ssl/certs/apache-selfsigned.crt", dest: "/etc/ssl/certs/apache-selfsigned.crt" }
        - { src: "/etc/apache2/sites-available/montp2.obtusk.com.conf", dest: "/etc/apache2/sites-available/montp2.obtusk.com.conf" }
        - { src: "/var/www/montp2.obtusk.com", dest: "/var/www/montp2.obtusk.com" }

    - name: Arrêt et suppression du conteneur temporaire
      docker_container:
        name: my_temp_container
        state: absent
