---
- name: Déploiement du conteneur
  hosts: all
  become: true

  tasks:
    - name: Installation de Docker
      apt:
        name: docker.io
        state: present

    - name: Extraction des configurations de l'image Docker
      docker_image:
        name:  lstar974/serveur
        source: extract
        src_path: "/etc/mysql/mariadb-config,/etc/ssl/private/apache-selfsigned.key,/etc/ssl/certs/apache-selfsigned.crt,/etc/apache2/sites-available/montp2.obtusk.com.conf"
      register: docker_extract_output

    - name: Copie des fichiers de configuration
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - { src: "/etc/mysql/mariadb-config", dest: "/etc/mysql/mariadb-config" }
        - { src: "/etc/ssl/private/apache-selfsigned.key", dest: "/etc/ssl/private/apache-selfsigned.key" }
        - { src: "/etc/ssl/certs/apache-selfsigned.crt", dest: "/etc/ssl/certs/apache-selfsigned.crt" }
        - { src: "/etc/apache2/sites-available/montp2.obtusk.com.conf", dest: "/etc/apache2/sites-available/montp2.obtusk.com.conf" }
      when: docker_extract_output is succeeded
