- name: Déploiement du conteneur
  hosts: all
  become: true

  tasks:
    - name: Sauvegarde de l'image Docker en tant que fichier tar
      command: docker save lstar974/serveur -o /root/serveur.tar

    - name: Copie du fichier tar sur la machine distante
      copy:
        src: /root/serveur.tar
        dest: /root/serveur.tar

    - name: Chargement de l'image Docker depuis le fichier tar
      command: docker load -i /root/serveur.tar

    - name: Création du conteneur temporaire
      docker_container:
        name: my_temp_container
        image: lstar974/serveur
        command: sleep infinity
        detach: yes
        privileged: yes
      register: temp_container_output

    - name: Copie des fichiers de configuration depuis le conteneur
      command: sh -c "docker cp my_temp_container:{{ item.src }} {{ item.dest }}"
      with_items: "{{ files_to_copy }}"
      vars:
        files_to_copy:
          - src: /etc/mysql/my.cnf
            dest: /etc/mysql
          - src: /etc/keys/montp2.obtusk.com.key
            dest: /etc/keys
          - src: /etc/keys/montp2.obtusk.com.crt
            dest: /etc/keys
          - src: /etc/apache2/sites-available/montp2.obtusk.com.conf
            dest: /etc/apache2/sites-available
          - src: /var/www/montp2.obtusk.com
            dest: /var/www
          - src: /etc/apache2/.htpasswd
            dest: /etc/apache2/

    - name: Arrêt et suppression du conteneur temporaire
      docker_container:
        name: my_temp_container
        state: absent

    - name: Suppression du fichier tar
      file:
        path: /root/serveur.tar
        state: absent
