- name: Déploiement du conteneur
  hosts: all
  become: true

  tasks:
    - name: Téléchargement de l'image Docker
      command: docker pull lstar974/serveur:latest
      
    - name: Sauvegarde de l'image Docker en tant que fichier tar
      command: docker save lstar974/serveur:latest -o /root/serveur.tar
      
    - name: Création du conteneur temporaire
      docker_container:
        name: my_temp_container
        image: lstar974/serveur:latest
        command: sleep infinity
        detach: yes
        privileged: yes
      register: temp_container_output
      
    - name: Installation de Certbot
      command: apt install certbot
      
    - name: Création du dossier traefik
      command: mkdir -p /etc/traefik
      args:
        creates: /etc/traefik

    - name: Création du dossier conf
      command: mkdir -p /etc/traefik/conf
      args:
        creates: /etc/traefik/conf
      
    - name: Attribution du propriétaire
      command: chown -R www-data:www-data /etc/traefik/conf

    - name: Copie des fichiers de configuration depuis le conteneur
      command: sh -c "docker exec -i my_temp_container tar -cf - {{ item.src }} | tar -xf - -C {{ item.dest }} --strip-components=3"
      with_items: "{{ files_to_copy }}"
      vars:
        files_to_copy:
          - src: /etc/mysql/my.cnf
            dest: /etc/mysql
          - src: /etc/apache2/sites-available/montp2.obtusk.com.conf
            dest: /etc/apache2/sites-available
          - src: /var/www/montp2.obtusk.com
            dest: /var/www
          - src: /usr/local/bin/traefik
            dest: /usr/local/bin/
          - src: /etc/traefik/conf/traefik.toml
            dest: /etc/traefik/conf/
          - src: /etc/apache2/password/.htpasswd
            dest: /etc/apache2/
          - src: /etc/traefik/.htpasswd
            dest: /etc/traefik/
            
    - name: Déplacement du contenu du dossier 'Site futur' vers '/var/www/montp2.obtusk.com'
      command: rsync -av --remove-source-files /var/www/Site\ futur/ /var/www/montp2.obtusk.com/
      
    - name: Suppression du dossier 'Site futur' (si nécessaire)
      file:
        path: /var/www/Site\ futur/
        state: absent
        
    - name: Activation du fichier de configuration montp2.obtusk.com.conf
      command: a2ensite montp2.obtusk.com.conf
      
    - name: Désactivation du fichier de configuration 000-default.conf
      command: a2dissite 000-default.conf
      
    - name: Reload du service Apache2
      command: systemctl reload apache2
      
    - name: Arrêt et suppression du conteneur temporaire
      docker_container:
        name: my_temp_container
        state: absent
