---
- name: Déploiement du conteneur
  hosts: all
  become: true

  tasks:
    - name: Installation de Docker
      apt:
        name: docker.io
        state: present

    - name: Démarrage du conteneur temporaire
      docker_container:
        name: my_app_container
        image: lstar974/serveur
        detach: yes
        privileged: yes
      register: temp_container_output

   - name: Extraction des fichiers de configuration du conteneur temporaire
  command: docker cp {{ temp_container_output.container.ID }}:/etc/mysql/my.cnf {{ item.dest }}
  loop:
    - { src: "/etc/mysql/my.cnf", dest: "/etc/mysql/my.cnf" }
    - { src: "/etc/ssl/private/apache-selfsigned.key", dest: "/etc/ssl/private/apache-selfsigned.key" }
    - { src: "/etc/ssl/certs/apache-selfsigned.crt", dest: "/etc/ssl/certs/apache-selfsigned.crt" }
    - { src: "/etc/apache2/sites-available/montp2.obtusk.com.conf", dest: "/etc/apache2/sites-available/montp2.obtusk.com.conf" }
  when: temp_container_output is succeeded

    - name: Arrêt et suppression du conteneur temporaire
      docker_container:
        name: my_app_container
        state: absent
