- name: Déploiement du conteneur
  hosts: all
  become: true

  tasks:
    - name: Installation de Docker
      apt:
        name: docker.io
        state: present

    - name: Démarrage du conteneur temporaire
      docker_container:
        name: my_app_container
        image: lstar974/serveur
        detach: yes
        privileged: yes
      register: temp_container_output

    - name: Vérification des emplacements des fichiers dans le conteneur temporaire
      shell: docker exec -it my_app_container ls {{ item }}
      loop:
        - /etc/mysql/my.cnf
        - /etc/ssl/private/apache-selfsigned.key
        - /etc/ssl/certs/apache-selfsigned.crt
        - /etc/apache2/sites-available/montp2.obtusk.com.conf
        - /var/www/montp2.obtusk.com

    - name: Extraction des fichiers de configuration du conteneur temporaire
      command: docker cp -L {{ temp_container_output.container.Id }}:{{ item.src }} {{ item.dest }}
      loop:
        - { src: "/etc/mysql/my.cnf", dest: "/etc/mysql/my.cnf" }
        - { src: "/etc/ssl/private/apache-selfsigned.key", dest: "/etc/ssl/private/apache-selfsigned.key" }
        - { src: "/etc/ssl/certs/apache-selfsigned.crt", dest: "/etc/ssl/certs/apache-selfsigned.crt" }
        - { src: "/etc/apache2/sites-available/montp2.obtusk.com.conf", dest: "/etc/apache2/sites-available/montp2.obtusk.com.conf" }
        - { src: "/var/www/montp2.obtusk.com", dest: "/var/www/montp2.obtusk.com" }
      when: extraction_result is succeeded
        

    - name: Arrêt et suppression du conteneur temporaire
      docker_container:
        name: my_app_container
        state: absent

