- name: Installation des packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - mariadb-server
    - php
    - libapache2-mod-php
    - php-mysql
    - openssl

- name: Enable Apache2 SSL module
  apache2_module:
    name: ssl
    state: present

- name: Create self-signed SSL certificate
  openssl_certificate:
    path_cert: /etc/ssl/certs/self-signed.crt
    path_key: /etc/ssl/private/self-signed.key
    common_name: "montp2.obtusk.com"
    subject_alt_name: "DNS:montp2.obtusk.com,DNS:matomo-montp2.obtusk.com"
    provider: selfsigned

- name: Copie des fichiers de configuration
  copy:
    src: "{{ item }}"
    dest: "/etc/apache2/sites-available/{{ item }}"
  with_items:
    - montp2.obtusk.com.conf
    - matomo-montp2.obtusk.com.conf
    - apache2.conf

- name: Configure montp2.obtusk.com virtualhost
  template:
    src: montp2.obtusk.com.conf.j2
    dest: /etc/apache2/sites-available/montp2.obtusk.com.conf
  notify: Reload Apache2

- name: Configure matomo-montp2.obtusk.com virtualhost
  template:
    src: matomo-montp2.obtusk.com.conf.j2
    dest: /etc/apache2/sites-available/matomo-montp2.obtusk.com.conf
  notify: Reload Apache2

- name: Activation des virtualhosts
  command: a2ensite {{ item }}
  with_items:
    - montp2.obtusk.com.conf
    - matomo-montp2.obtusk.com.conf

- name: Désactivation du site par défaut
  command: a2dissite 000-default.conf

- name: Redémarrage d'Apache
  service:
    name: apache2
    state: restarted

- name: Installation de Matomo
  unarchive:
    src: "https://builds.matomo.org/matomo-latest.zip"
    dest: "/var/www/matomo-montp2.obtusk.com"
    remote_src: yes
    creates: "/var/www/matomo-montp2.obtusk.com/piwik.php"

- name: Configuration de Matomo
  command: php /var/www/matomo-montp2.obtusk.com/console config:set --section=database --key=dbname --value=matomo
  environment:
    MYSQL_PWD: root

- name: Création de la base de données pour Matomo
  command: mysql -uroot -e "CREATE DATABASE IF NOT EXISTS matomo;"
  environment:
    MYSQL_PWD: root

- name: Redémarrage du serveur MariaDB
  service:
    name: mariadb
    state: restarted
