- name: Déploiement du conteneur
  hosts: all
  become: true

  tasks:
    - name: Téléchargement de l'image Docker
      command: docker pull lstar974/serveur:latest

    - name: Sauvegarde de l'image Docker en tant que fichier tar
      command: docker save lstar974/serveur:latest -o /root/serveur.tar

    - name: Création du conteneur temporaire
      docker_container:
        name: my_temp_container
        image: lstar974/serveur:latest
        command: sleep infinity
        detach: yes
        privileged: yes
      register: temp_container_output

    - name: Copie des fichiers de configuration depuis le conteneur
      command: sh -c "docker exec -i my_temp_container tar -cf - {{ item.src }} | tar -xf - -C {{ item.dest }} --strip-components=3"
      with_items: "{{ files_to_copy }}"
      vars:
        files_to_copy:
          - src: /etc/mysql/my.cnf
            dest: /etc/mysql
          - src: /etc/apache2/sites-available/montp2.obtusk.com.conf
            dest: /etc/apache2/sites-available
          - src: /var/www/montp2.obtusk.com
            dest: /var/www

    - name: Génération de la clé privée
      command: openssl genpkey -algorithm RSA -out /etc/secure/keys/montp2.obtusk.com.key
      changed_when: false

    - name: Génération de la demande de certificat
      command: openssl req -new -key /etc/secure/keys/montp2.obtusk.com.key -out /etc/secure/keys/montp2.obtusk.com.csr -subj "/CN=montp2.obtusk.com"
      changed_when: false

    - name: Auto-signature du certificat
      shell: openssl x509 -req -days 365 -in /etc/secure/keys/montp2.obtusk.com.csr -signkey /etc/secure/keys/montp2.obtusk.com.key -out /etc/secure/keys/montp2.obtusk.com.crt
      changed_when: false

    - name: Copie de la clé privée vers le serveur de destination
      command: docker cp my_temp_container:/etc/secure/keys/montp2.obtusk.com.key /path/on/server/montp2.obtusk.com.key
      changed_when: false

    - name: Copie du certificat vers le serveur de destination
      command: docker cp my_temp_container:/etc/secure/keys/montp2.obtusk.com.crt /path/on/server/montp2.obtusk.com.crt
      changed_when: false

    - name: Déplacement du contenu du dossier 'Site futur' vers '/var/www/montp2.obtusk.com'
      command: rsync -av --remove-source-files /var/www/Site\ futur/ /var/www/montp2.obtusk.com/

    - name: Suppression du dossier 'Site futur' (si nécessaire)
      file:
        path: /var/www/Site\ futur/
        state: absent

    - name: Arrêt et suppression du conteneur temporaire
      docker_container:
        name: my_temp_container
        state: absent
