- name: Deploy Application
  hosts: 192.168.6.50
  remote_user: lucas
  become: true

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: lstar974/serveur
        source: pull

    - name: Run Docker Container
      docker_container:
        name: my_app_container
        image: lstar974/serveur
        ports:
          - "60:60"
