---
- name: Déploiement du conteneur
  hosts: all
  become: true

  tasks:
    - name: Installation de Docker
      apt:
        name: docker.io
        state: present

    - name: Démarrage d'un conteneur temporaire pour extraire les fichiers de configuration
      docker_container:
        name: my_app_container
        image: lstar974/server
        command: sleep infinity
        detach: true
      register: container_output

    - name: Extraction des fichiers de configuration du conteneur temporaire
      docker_cp:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        container: temp_container.id
      loop:
        - { src: "/etc/mysql/mariadb-config", dest: "/etc/mysql/mariadb-config" }
        - { src: "/etc/ssl/private/apache-selfsigned.key", dest: "/etc/ssl/private/apache-selfsigned.key" }
        - { src: "/etc/ssl/certs/apache-selfsigned.crt", dest: "/etc/ssl/certs/apache-selfsigned.crt" }
        - { src: "/etc/apache2/sites-available/montp2.obtusk.com.conf", dest: "/etc/apache2/sites-available/montp2.obtusk.com.conf" }
      when: container_output is succeeded

    - name: Arrêt et suppression du conteneur temporaire
      docker_container:
        name: my_app_container
        state: absent
