- name: Déploiement du conteneur
  hosts: all
  become: true

  tasks:
    - name: Installation de Docker
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Ajout de la clé GPG Docker
      become: yes
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Ajout du référentiel Docker
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Installation de Docker
      become: yes
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Démarrage et autorisation de Docker
      command:
        cmd: "systemctl start docker"
      become: true

    - name: Activation du démarrage automatique de Docker
      command:
        cmd: "systemctl enable docker"
      become: true

    - name: Installation de Python
      apt:
        name: python3-pip
        state: present
        
    - name: Installation de Python
      apt:
        name: python3-pip
        state: present

    - name: Installation du module Docker
      pip:
        name: docker
        state: present
        
    - name: Installation des dépendances
      apt:
        name: ['python3', 'python3-pip']
        state: present

    - name: Installation de Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3
      
    - name: Téléchargement de l'image Docker
      command: docker pull lstar974/serveur:latest
      
    - name: Sauvegarde de l'image Docker en tant que fichier tar
      command: docker save lstar974/serveur:latest -o /root/serveur.tar
      
    - name: Création du conteneur temporaire
      docker_container:
        name: my_temp_container
        image: lstar974/serveur:latest
        command: sleep infinity
        detach: yes
        privileged: yes
      register: temp_container_output
      
    - name: Installation de Certbot
      apt:
        name: certbot
        state: present


    - name: Enregistrement du compte Let's Encrypt avec Certbot
      command: certbot register --agree-tos --email lucas.buchle@gmail.com
      become: true
      
    - name: Copie des fichiers de configuration depuis le conteneur
      command: sh -c "docker exec -i my_temp_container tar -cf - {{ item.src }} | tar -xf - -C {{ item.dest }} --strip-components=3"
      with_items: "{{ files_to_copy }}"
      vars:
        files_to_copy:
          - src: /etc/apache2/sites-available/montp2.obtusk.com.conf
            dest: /etc/apache2/sites-available
          - src: /var/www/montp2.obtusk.com
            dest: /var/www/montp2.obtusk.com
          - src: /etc/apache2/password/.htpasswd
            dest: /etc/apache2/
          - src: /etc/web/serveur/traefik
            dest: /root/
          
    - name: Suppression du dossier 'Site futur' (si nécessaire)
      file:
        path: /var/www/Site\ futur/
        state: absent
        
    - name: Suppression du conteneur existant
      command: docker rm -f traefik
      
    - name: Activation du fichier de configuration montp2.obtusk.com.conf
      command: a2ensite montp2.obtusk.com.conf
      
    - name: Désactivation du fichier de configuration 000-default.conf
      command: a2dissite 000-default.conf
      
    - name: Démarrage Apache2
      command: systemctl start apache2
      
    - name: Reload Apache2
      command: systemctl reload apache2
      
    - name: Désactivation Apache2
      command: systemctl stop apache2
      
    - name: Suppression du réseau web existant
      command: docker network rm web
      ignore_errors: true
      
    - name: Création du réseau web
      command: docker network create web
      
    - name: Création du volume
      command: docker volume create traefik_config
      
    - name: Installation du conteneur Traefik
      command: /usr/local/bin/docker-compose -f /root/traefik/docker-compose.yaml up -d
    
    - name: Arrêt et suppression du conteneur temporaire
      docker_container:
        name: my_temp_container
        state: absent
