- name: Déploiement du conteneur
  hosts: all
  become: true

  tasks:
    - name: Sauvegarde de l'image Docker en tant que fichier tar
      command: docker save lstar974/serveur -o /root/serveur.tar

    - name: Création du conteneur temporaire
      docker_container:
        name: my_temp_container
        image: lstar974/serveur
        command: sleep infinity
        detach: yes
        privileged: yes
      register: temp_container_output

    - name: Copie des fichiers de configuration depuis le conteneur
      command: sh -c "docker exec -i my_temp_container tar -cf - {{ item.src }} | tar -xf - -C {{ item.dest }}"
      with_items: "{{ files_to_copy }}"
      vars:
        files_to_copy:
          - src: /etc/mysql/my.cnf
            dest: /etc/mysql
          - src: apache-selfsigned.key
            dest: /etc/ssl/private
          - src: apache-selfsigned.crt
            dest: /etc/ssl/certs
          - src: montp2.obtusk.com.conf
            dest: /etc/apache2/sites-available
          - src: montp2.obtusk.com
            dest: /var/www

    - name: Arrêt et suppression du conteneur temporaire
      docker_container:
        name: my_temp_container
        state: absent
